name: Build and publish Songboard bundle

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Prepare distribution bundle
        run: |
          set -euo pipefail
          mkdir -p build
          cp songlink_clipboard_watcher.py dist/INSTALLATION.md build/
          pushd build >/dev/null
          zip -r songboard-macos.zip songlink_clipboard_watcher.py INSTALLATION.md
          rm songlink_clipboard_watcher.py INSTALLATION.md
          cat <<'EOF' > index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Songboard Bundle</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
      :root { color-scheme: dark light; font-family: -apple-system, BlinkMacSystemFont, "Helvetica Neue", Helvetica, Arial, sans-serif; }
      body { margin: 0; padding: 48px 16px; display: flex; flex-direction: column; align-items: center; background: radial-gradient(circle at top, #203a5c 0%, #111421 60%, #0b0d16 100%); color: #f5f7ff; min-height: 100vh; }
      h1 { margin: 0 0 8px; font-size: clamp(2rem, 4vw, 3rem); letter-spacing: -0.02em; }
      p { margin: 0 0 32px; max-width: 480px; text-align: center; opacity: 0.85; line-height: 1.6; }
      a.button { display: inline-flex; align-items: center; gap: 12px; padding: 16px 28px; border-radius: 999px; font-weight: 600; text-decoration: none; background: linear-gradient(130deg, #8bc6ec, #6279ff); color: #05060c; box-shadow: 0 12px 40px -12px rgba(137, 152, 252, 0.6); transition: transform 0.15s ease, box-shadow 0.15s ease; }
      a.button:hover { transform: translateY(-1px); box-shadow: 0 18px 48px -14px rgba(137, 152, 252, 0.5); }
      .note { margin-top: 48px; font-size: 0.9rem; opacity: 0.65; }
    </style>
  </head>
  <body>
    <h1>Songboard for macOS</h1>
    <p>Download the latest Songboard bundle containing the clipboard watcher script and guided installation steps. Perfect for Gumroad deliveries or direct downloads.</p>
    <a class="button" href="songboard-macos.zip" download>Download Songboard Bundle</a>
    <p class="note">Updated automatically each time the repository changes.</p>
  </body>
</html>
EOF
          popd >/dev/null

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
