name: Build and publish Songboard bundle

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build distribution bundle
        run: |
          set -euo pipefail
          mkdir -p build
          cp songlink_clipboard_watcher.py dist/INSTALLATION.md build/
          pushd build >/dev/null
          zip -r songboard-macos.zip songlink_clipboard_watcher.py INSTALLATION.md
          popd >/dev/null

      - name: Publish GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: bundle
          name: Songboard bundle
          body: Automated bundle used for Gumroad and direct downloads.
          draft: false
          prerelease: false
          allowUpdates: true
          removeArtifacts: true
          artifacts: build/songboard-macos.zip
